home:
  platform:
    addr: http://127.0.0.1:8090
    register-route: /sxdemo/register
  services:
    node:
      id: i-am-the-first-node
      name: i-really-am-the-first-node
      namespace: sz-home
      address:
        protocol: http
        address: 127.0.0.1:8090
      version: 1.0
      metadata:
        key: hello
        hi: OK
  files:
    tmp:
      isTmp: true
    #  dir: E:\Projects\home\files\tmp
      dir: /Users/shuxian/Projects/joincloud/files/tmp
    photo:
      isTmp: false
    #  dir: E:\Projects\home\files\photo
      dir: /Users/shuxian/Projects/joincloud/files/photo

